x-nginx_environment: &nginx_environment
  environment:
    - ENVIRONMENT=development
    - TLS_MODE=${TLS_MODE:-off}
    - HTPASSWD_NODE
    - HTPASSWD
    - SITE_HOST=localhost


services:
  frontend:
    build:
      context: ./frontend
    image: my-docs-frontend:local
    volumes:
      - site-data:/srv/site
    command: ["sleep", "infinity"]  # builder container: build with docker compose exec

  nginx:
    build:
      context: ./nginx
    image: my-docs-nginx:local
    ports:
      - "8080:80"
    volumes:
      - site-data:/var/www/local_static/
    depends_on:
      - frontend
    <<: *nginx_environment


volumes:
  site-data:
