x-nginx_environment: &nginx_environment
  environment:
    - ENVIRONMENT=development
    - TLS_MODE=${TLS_MODE:-off}
    - HTPASSWD_NODE
    - HTPASSWD
    - SITE_HOST=localhost


services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    image: my-docs-frontend:local
    volumes:
      - site-data:/srv/site
    command: ["sleep", "infinity"]  # builder container: we will run build with docker-compose exec

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    image: my-docs-nginx:local
    ports:
      - "8080:80"
    volumes:
      - site-data:/var/www/local_static/:ro
    depends_on:
      - frontend
    <<: *nginx_environment


volumes:
  site-data:
